config/routes.rb
Rails.application.routes.draw do

  resources :microposts

  resources :users

  get 'static_pages/etusivu'

  get 'static_pages/esittely'

  get 'static_pages/palvelut'

  get 'static_pages/tarjous'

  get 'static_pages/linkit'

  get 'static_pages/info'

  get 'static_pages/galleria'

  root 'static_pages#esittely'

  match '/etusivu',        to: 'static_pages#etusivu',        via: 'get'
  match '/esittely',        to: 'static_pages#esittely',        via: 'get'
  match '/palvelut',     to: 'static_pages#palvelut',     via: 'get'
  match '/info',     to: 'static_pages#info',     via: 'get'
  match '/tarjous',       to: 'static_pages#tarjous',       via: 'get'
  match '/linkit',  to: 'static_pages#linkit',  via: 'get'
  match '/galleria',    to: 'static_pages#galleria',    via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def etusivu
  end

  def esittely
  end

  def yhteys
  end

  def galleria
  end

  def linkit
  end

  def tarjous
  end

  def palvelut
  end

  def send_form_email
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	
    <div class="footer-container">
    </div>
    
    <div class="menu-container">
        <div class="menu">
    	
<!--ETUSIVU -->

<%= link_to content_tag(:span, 'ETUSIVU'), etusivu_path , :id=>"etusivu-link"%>

<!--ESITTELY -->

<% if current_page?(esittely_path) || current_page?(root_path) %>
		<%= link_to content_tag(:span, 'Esittely'), "#", :class=>"selected" %>
<% else %>
		<%= link_to content_tag(:span, 'Esittely'), esittely_path %>
<% end %>

<!--PALVELUT -->

<% if current_page?(palvelut_path) %>
		<%= link_to content_tag(:span, 'Palvelut'), "#", :class=>"selected" %>
<% else %>
		<%= link_to content_tag(:span, 'Palvelut'), palvelut_path %>
<% end %>

<!--GALLERIA-->

<!--
<% if current_page?(galleria_path) %>
		<%= link_to content_tag(:span, 'GALLERIA'), "#", :class=>"selected" %>
<% else %>
		<%= link_to content_tag(:span, 'GALLERIA'), galleria_path %>
<% end %>
-->

<!--LINKIT-->

<% if current_page?(linkit_path) %>
		<%= link_to content_tag(:span, 'Linkit'), "#", :class=>"selected" %>
<% else %>
		<%= link_to content_tag(:span, 'Linkit'), linkit_path %>
<% end %>

<!--TARJOUS-->

<% if current_page?(tarjous_path) %>
		<%= link_to content_tag(:span, 'Tarjous'), "#", :class=>"selected" %>
<% else %>
		<%= link_to content_tag(:span, 'Tarjous'), tarjous_path %>
<% end %>

<!--CONTACT-->

<% if current_page?(info_path) %>
		<%= link_to content_tag(:span, 'Info'), "#", :class=>"selected" %>
<% else %>
		<%= link_to content_tag(:span, 'Info'), info_path %>
<% end %>

		</div>
	</div>
</div>

app/views/layouts/_logosmall.html.erb
<div class="logo-small">
		<a href="mailto:tommi.tiihonen@gmail.com?subject=Palautetta/kysymyksiä" target="_blank" title="Lähetä sähköpostia Tommille" alt="Lähetä sähköpostia Tommille">
			<%=image_tag("logos/small/music-studio-small.png")%>
		</a>
</div>

app/views/layouts/_pagetop.html.erb
<script type="text/javascript">
	$(document).ready(function() {
		$('#pages').hide().fadeIn(800);
	});
</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_tausta.html.erb
<div class="wrapper-tausta">

	<div class="tausta">
	</div>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8">

  <title>MUSIC STUDIO | <%= yield(:title) %></title>
  
  <%= favicon_link_tag 'ICON-music-studio.ico' %>  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  
  <%= set_meta_tags :description => "Musiikin miksausta, editointia ja masterointia ammattitaidolla, kustannustehokkaaseen hintaan ja viimeisintä teknologiaa ja ohjelmistoja käyttäen." %>
<!--  <%= set_meta_tags :keywords => %w[kotisivut websivut suunnittelu ylläpito editointi palvelu grafiikka valokuvat videot mainonta facebook google optimointi] %>
-->
  
</head>

<body>

<!--[if gte IE 9]>
  <style type="text/css">
    .gradient {
       filter: none;
    }
  </style>
<![endif]-->

<div class="background"></div>
<div class="intro"></div>
<div class="intro-gradientcorners"></div>


<%= render "/layouts/tausta" %>

<div class="wrapper-content">
	<div class="content">
		<%= yield %>
	</div>
</div>

<%= render "/layouts/footer" %>

<%= render "/layouts/logosmall" %>

</body>
</html>

app/views/static_pages/esittely.html.erb
<% provide(:title, 'Esittely') %>

<%= render "/layouts/pagetop" %>

<table align="center" id="pages" class="taulukko" cellspacing="0" cellpadding="20">
	<tr>
		<td class="otsikko">
			<h1>ESITTELY</h1>
		</td>
	</tr>

	<tr>
		<td class="content-back">

			<div style="padding-top:10px; text-align: center" class="small">    
				<%=image_tag("tommi.png", alt: "Tommi Tiihonen")%>

				<p></p>
      
				<span class="highlight">
					<strong>Tommi Tiihonen</strong>
				</span>
					<br />
					Musiikin miksaus-, tuotanto- ja masterointipalvelut /<br>graafinen- ja videoiden suunnittelu ja editointi / Web-palvelut
			</div>

			<div style="text-align: justify;">

				<hr size="1" noshade />

				<p>Tähän osoitteeseen avataan tulevaisuudessa <span class="highlight">MUSIC STUDIO</span>:n websivut. 
					Yritys ei ole vielä aktiivinen, mutta lähitulevaisuudessa.</p>
				<p>MUSIC STUDIO tulee olemaan yksi kolmesta yrityksestäni, ja on keskittynyt Audio-materiaalin äänittämiseen, editoimiseen 
					(<span class="highlight small" style="font-style: italic">MIDI-lisäinstrumentit, kuten Syntetisaattori, Piano, Basso, Viulut ym. orkesteri-instrumentit jne.</span>), 
					miksaamiseen ja masterointiin. 
					Muut yritykseni ovat <span class="highlight">WEB STUDIO</span> ja <span class="highlight">CREATIVE STUDIO</span>, 
					joihin pääset tutustumaan <span class="highlight"><strong>ETUSIVU</strong></span> linkin kautta.

				<p>Saat kauttani ensiluokkaista musiikin tuottamista viimeisimmillä ohjelmilla <span class="highlight">
					(Cubase 8.0.5, LINE 6, iZotope 6, Halion Symphonic Orchestra, Halion Sonic)</span>, useiden vuosien kokemuksella ja ammattitaidolla. 
					Ylläpidän osaamistani jatkuvasti sekä huolehdin myös siitä, että ohjelmistoni ovat aina ajan tasalla.</p>

				<p class="small">
					<span style="font-style: italic">Whatever You wish I can deliver</i>
				</p>

			</div>
		</td>
	</tr>

<%= render "/layouts/textbottom" %>

</table>

app/views/static_pages/etusivu.html.erb
<script type="text/javascript">
	window.location.replace("index.html");
</script>

app/views/static_pages/galleria.html.erb
<% provide(:title, 'Galleria') %>

<%= render "/layouts/pagetop" %>

<table align="center" id="pages" class="taulukko" cellspacing="0" cellpadding="20">
  <tr>
    <td class="otsikko">
    	<h1>GALLERIA</h1>
    </td>
  </tr>
  
  <tr>
  	<td>
        

<div align="center">

	<br>Tommi Tiihonen
	<br>Maasälväntie 2 A 1, 00710 Helsinki
	<br>E-mail: tommi.tiihonen@gmail.com
	<br>Puh.: 040-5358532

	<p>Facebook: www.facebook.com/rockworksstudio</p>

</div>

	</td>
	</tr>

<%= render "/layouts/textbottom" %>
    
</table>

app/views/static_pages/info.html.erb
<% provide(:title, 'Info') %>		
		
<%= render "/layouts/pagetop" %>

<table align="center" id="pages" class="taulukko" cellspacing="0" cellpadding="20">
  <tr>
    <td class="otsikko">
    	<h1>INFO</h1>
    </td>
  </tr>
  
  <tr>
  	<td>
        

<div align="center">

	<p class="highlight">Tommi Tiihonen
	<br>Maasälväntie 2 A 1
	<br>00710 Helsinki
	</p>

	<p>E-mail:
		<br><a href="mailto:tommi.tiihonen@gmail.com?subject=feedback" target="_blank">tommi.tiihonen@gmail.com</a>
	</p>
		
	<p>Puh.:
		<br><span class="highlight">040-5358532</span>
	</p>
	
	<p>Facebook:
		<br><a href="http://www.facebook.com/rockworksstudio" target="_blank">www.facebook.com/rockworksstudio</a>
	</p>

</div>

    </td>
  </tr>
  
<%= render "/layouts/textbottom" %>  
  
</table>

app/views/static_pages/intro.html.erb
<% provide(:title, 'Tervetuloa WEB-STUDIO:n kotisivuille!') %>

<%= render "/layouts/pagetop" %>

<table align="center" id="pages" class="taulukko" cellspacing="0" cellpadding="20">
  <tr>
    <td class="otsikko">
    	<h1>Tervetuloa WEB-STUDIO:n kotisivuille!</h1>
    </td>
  </tr>
  
  <tr>
  	<td>
        
    <div style="padding-top:10px; text-align: center" class="small">    
      <%=image_tag("tommi.png", alt: "Tommi Tiihonen")%>
      <p></p>
      
      <span class="highlight">
      <strong>Tommi Tiihonen</strong>
      
      <br />Web-suunnittelu / graafinen suunnittelu / videot / Facebook-promootio
      </span>
      
    </div>
    


	<div style="text-align: justify;">

	    <hr size="1" noshade />

	      <p>Tähän osoitteeseen avataan tulevaisuudessa <span class="highlight">WEB-STUDIO</span>:n websivut. Yritys ei ole vielä aktiivinen, mutta lähitulevaisuudessa.</p>
	      <p>WEB-STUDIO tulee olemaan yksi kolmesta yrityksestäni, ja on keskittynyt Web-editointiin ja sosiaaliseen mediaan.
	      	 Muut yritykseni ovat <span class="highlight">MUSIC-STUDIO</span> (musiikin miksaus) ja <span class="highlight">CREATIVE-STUDIO</span> (mediatuotanto). 
	      	 Yritysten nimet kertonevat hyvin palvelustani.</p>
	      <p>Saat kauttani tulevaisuudessa Web-sivut ja vaikka Chat-sovelluksen kotisivuillesi. Ja mikä parasta, teen Google-optimoinnin ja peruspromootion kaupan päälle.</p>
	      <p>Tutustu myös muihin palveluihini!</p>
	      <p class="small">
	      	<i>Whatever You wish I can deliver.</i>
	      </p>

	</div>

    </td>
  </tr>  		
  		
  	</td>
  </tr>
  
</table>

app/views/static_pages/linkit.html.erb
<% provide(:title, 'Laitteisto') %>

<%= render "/layouts/pagetop" %>

<table align="center" id="pages" class="taulukko" cellspacing="0" cellpadding="20">
  <tr>
    <td class="otsikko">
    	<h1>LINKIT</h1>
    </td>
  </tr>
  
  <tr>
  	<td>
        

<div align="center">

<p>Coming soon!</p>

</div>

    </td>
  </tr>

<%= render "/layouts/textbottom" %>  
  
</table>

app/views/static_pages/palvelut.html.erb
<% provide(:title, 'Palvelut') %>

<%= render "/layouts/pagetop" %>

<table align="center" id="pages" class="taulukko" cellspacing="0" cellpadding="20">
  <tr>
    <td class="otsikko">
    	<h1>PALVELUT</h1>
    </td>
  </tr>
  
  <tr>
  	<td>
        

<div>

<p>Tarjoan teille seuraavia WEB-palveluja:</p>

	<ul>
		<li>WEB-sivut</li>
		<li>Oma verkkokauppa</li>
		<li>Oma keskustelupalsta</li>
		<li>Käyttäjärekisteröityminen</li>
		<li>Grafiikat / muu media</li>
		<li>Facebook-promootio (ym. Sosiaalinen Media)</li>
		<li>GOOGLE-optimointi ja -markkinointi</li>
		<li>Sivustotilastot</li>
	</ul>
	
<p>Lähetä halutessasi Tarjouspyyntölomakkeen kautta lisäkysymyksiä. INFO-sivulta löydät myös puhelinnumeroni ja sähköpostiosoitteeni.</p>

<p>Pystyn tarvittaessa tekemään sivut ilman ulkopuolista apua myös laadukkaalla Englannin kielellä.</p>

</div>

    </td>
  </tr>
  
<%= render "/layouts/textbottom" %>
  
</table>

app/views/static_pages/tarjous.html.erb
<% provide(:title, 'Tarjouspyyntö') %>		
		
<%= render "/layouts/pagetop" %>

<!--
	
	<head>

	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	
	<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.js"></script>
	
</head>


<div id="herjat"></div>

-->

<table align="center" id="pages" class="taulukko" cellspacing="0" cellpadding="20">

		<tr>
	    	<td class="otsikko">
				<h1>TARJOUSPYYNTÖ</h1>
			</td>
		</tr>
	  
		<tr>
		  	<td>
				<div align="left">
		
	<form name="contactform" action="send_form_email.php" method="post" id="contactform">
				  
				<p id="offer-otsikko">Pyydä tarjous:</p>
					  
				<p>
				    
				    <label>
				      <input type="checkbox" id="web" name="web" class="free" value="YES"/>
				      Kotisivuista
				    </label>
				  
				<br>
				    
				    <label>
				      <input type="checkbox" id="google" name="google" class="free" value="YES"/>
				      WEB-promootiosta (Facebook, Twitter, Google, jne.)
				    </label>
				    
				<br>
				    
				    <label>
				      <input type="checkbox" id="miksaus" name="miksaus" class="free" value="YES"/>
					  Musiikin miksauksesta ja/tai masteroinnista
				    </label>
				  
				<br>

				    <label>
				      <input type="checkbox" id="grafiikka" name="grafiikka" class="free" value="YES"/>
				      Grafiikan tai videon suunnittelusta ja/tai editoinnista
				    </label>
				    
				<br>
				    
				    <label>
				      <input type="checkbox" id="promo" name="promo" class="free" value="YES"/>
				      Media-promootiosta (levy-yhtiöt, radiot, lehdet yms.)
				    </label>
				  
				</p>
					  
				<p id="offer-otsikko">Pyydä infoa:</p>
				
			    <p>
				    
				    <label>
				        <input type="checkbox" id="general" name="general" class="free" value="YES"/>
				        Yleistä kysyttävää
					</label>
				    
				      <br />
				      
					<label>
				        <input type="checkbox" id="info" name="info" class="free" value="YES"/>
				        Lisätietoja palveluista
					</label>
				    
			    </p>  
				
	
			    <p id="offer-otsikko">
			       	<label style="font-size: 1em" for="toive">Lisätietoja ja toiveita:</label>

					<br />

					<textarea name="toive" id="toive" style="width: 100%; margin-top: 4px" rows="8"></textarea>
				</p>
	
	
	
				<p id="offer-otsikko" style="padding-top: 15px">Yhteystiedot:</p>
				  
				  
				  <table style="margin-top: 14px; background-color: rgba(0,0,0,0.3)" width="100%" border="0" cellspacing="8">
				    <tr>
				      <td align="right" class="textdown"><strong>E-mail*:</strong></td>
				      <td><input style="width: 260px; height: 12px" name="email" type="email" required id="email" form="contactform" autocomplete="on"></td>
				    </tr>
				    <tr>
				      <td align="right" class="textdown">Nimi:</td>
				      <td><input style="width: 260px; height: 12px" name="etunimi" type="text" id="etunimi" form="contactform" autocomplete="on"></td>
				    </tr>
				    <tr>
				      <td align="right" class="textdown">Puhelin:</td>
				      <td><input style="width: 260px; height: 12px" name="telephone" type="tel" id="telephone" form="contactform"></td>
				    </tr>
				  </table>
								
				<p align="center">
				    <input id="laheta" type="submit" value="Lähetä">
				      </input>
				</p>
				<p align="center">
				    <input id="tyhjenna" type="reset" value="Tyhjennä">
				    </input>
				</p>


				</form>
	
			</div>
			
		</td>
	</tr>
	
<%= render "/layouts/textbottom" %>
	
</table>